In this notebook we will adjust one of the txt files from Retrosheets into a csv format to then operate with in SQL! For this file we are looking at gl2022 (gamelogs from 2022)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/turnandbern/CS215/Project 7/alldata/gamelogs/gl2022.txt") 
df

,20220407,0,Thu,SDN,NL,1,ARI,NL.1,1.1,2,...,Seth Beer.1,10.1,ellid002,Drew Ellis,5.3,perdg001,Gerardo Perdomo,6.4,Unnamed: 159,Y
0,20220407,0,Thu,CIN,NL,1,ATL,NL,1,6,...,Travis d'Arnaud,2,dicka001,Alex Dickerson,10,swand001,Dansby Swanson,6,NaN,Y
1,20220407,0,Thu,MIL,NL,1,CHN,NL,1,4,...,Jason Heyward,8,wisdp001,Patrick Wisdom,5,hoern001,Nico Hoerner,6,NaN,Y
2,20220407,0,Thu,PIT,NL,1,SLN,NL,1,0,...,Yadier Molina,2,badeh001,Harrison Bader,8,edmat001,Tommy Edman,4,NaN,Y
3,20220407,0,Thu,NYN,NL,1,WAS,NL,1,5,...,Maikel Franco,5,escoa003,Alcides Escobar,6,roblv001,Victor Robles,8,NaN,Y
4,20220407,0,Thu,HOU,AL,1,ANA,AL,1,3,...,Max Stassi,2,marsb002,Brandon Marsh,9,fletd002,David Fletcher,6,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2424,20221005,0,Wed,KCA,AL,162,CLE,AL,162,2,...,Will Brennan,7,maill001,Luke Maile,2,stram002,Myles Straw,8,NaN,Y
2425,20221005,0,Wed,PHI,NL,162,HOU,AL,162,2,...,Jake Meyers,8,dubom001,Mauricio Dubon,6,maldm001,Martin Maldonado,2,NaN,Y
2426,20221005,0,Wed,ANA,AL,162,OAK,AL,162,2,...,Conner Capel,9,garcd004,Dermis Garcia,3,allen002,Nick Allen,6,NaN,Y
2427,20221005,0,Wed,DET,AL,162,SEA,AL,162,4,...,Abraham Toro,5,casac001,Curt Casali,2,crawj002,J.P. Crawford,6,NaN,Y
2428,20221005,0,Wed,NYA,AL,162,TEX,AL,162,2,...,Charlie Culberson,7,tavel001,Leody Taveras,8,thomb003,Bubba Thompson,9,NaN,Y

Here we see there are currently no headings represented in this txt file: We'll convert it and some work on it!

In [3]:
df.to_csv('gl2022.csv',  index = None)

In [4]:
df_1 = pd.read_csv("gl2022.csv")
df_1

,20220407,0,Thu,SDN,NL,1,ARI,NL.1,1.1,2,...,Seth Beer.1,10.1,ellid002,Drew Ellis,5.3,perdg001,Gerardo Perdomo,6.4,Unnamed: 159,Y
0,20220407,0,Thu,CIN,NL,1,ATL,NL,1,6,...,Travis d'Arnaud,2,dicka001,Alex Dickerson,10,swand001,Dansby Swanson,6,NaN,Y
1,20220407,0,Thu,MIL,NL,1,CHN,NL,1,4,...,Jason Heyward,8,wisdp001,Patrick Wisdom,5,hoern001,Nico Hoerner,6,NaN,Y
2,20220407,0,Thu,PIT,NL,1,SLN,NL,1,0,...,Yadier Molina,2,badeh001,Harrison Bader,8,edmat001,Tommy Edman,4,NaN,Y
3,20220407,0,Thu,NYN,NL,1,WAS,NL,1,5,...,Maikel Franco,5,escoa003,Alcides Escobar,6,roblv001,Victor Robles,8,NaN,Y
4,20220407,0,Thu,HOU,AL,1,ANA,AL,1,3,...,Max Stassi,2,marsb002,Brandon Marsh,9,fletd002,David Fletcher,6,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2424,20221005,0,Wed,KCA,AL,162,CLE,AL,162,2,...,Will Brennan,7,maill001,Luke Maile,2,stram002,Myles Straw,8,NaN,Y
2425,20221005,0,Wed,PHI,NL,162,HOU,AL,162,2,...,Jake Meyers,8,dubom001,Mauricio Dubon,6,maldm001,Martin Maldonado,2,NaN,Y
2426,20221005,0,Wed,ANA,AL,162,OAK,AL,162,2,...,Conner Capel,9,garcd004,Dermis Garcia,3,allen002,Nick Allen,6,NaN,Y
2427,20221005,0,Wed,DET,AL,162,SEA,AL,162,4,...,Abraham Toro,5,casac001,Curt Casali,2,crawj002,J.P. Crawford,6,NaN,Y
2428,20221005,0,Wed,NYA,AL,162,TEX,AL,162,2,...,Charlie Culberson,7,tavel001,Leody Taveras,8,thomb003,Bubba Thompson,9,NaN,Y

Again we confirm the issues with things in terms of column headings... this could be fixed in excel which will be  or could also do in notebook!For the sake of the exercise we may just utilize the columns as they are as headings as not described in grave detail and hefty length of headings. Would have to look at gamelog documentation for the names so most likely will utilize the autodetected schema headings as can interpret. (Trying to work with what given and scope/focus of project). Additionally while with propoer headings this datatable fits into the relational database based of of playerID/coachID, however do to the aforementioned issues with field headings, queries will be compiled from the two other datasets.

Professor WB has been added as a principal on the Retrosheet_Dataset of Google Cloud. Queries for the project are listed in the Dataset Queries tab. If issues are had accessing this, I will be more than ready to aid in any issue!

The queries can also be accessed via this link: https://console.cloud.google.com/bigquery?sq=566683647345:305f78f7dee4439b81191d715f22688f